const humorousExistentialQuestions = [
  "What if the universe is just someone's overly long Netflix binge?",
  "Is life just one giant loading screen?",
  "Do my socks disappear to a parallel universe?",
  "If I'm 70% water, does that make me technically a waterbed?",
  "Is free will just the universe letting me pretend I know what I'm doing?",
  "If I eat a salad, does that make me morally superior to my past self?",
  "Am I living life, or just buffering?",
  "If the universe is infinite, does that mean somewhere out there, I have my life together?",
  "What if the meaning of life is just ‘42,’ and we missed the joke?",
  "Am I procrastinating on purpose or is the universe just stalling me?",
  "Do I think deep thoughts, or do deep thoughts think me?",
  "If time is a flat circle, why do I still have to wait in line?",
  "Is the Matrix real, and is that why my WiFi is always slow?",
  "If a tree falls in the forest and nobody tweets about it, does it really happen?",
  "Am I destined for greatness, or just to hit snooze 14 times?",
  "Why do I always find enlightenment in the shower and nowhere else?",
  "If I can't find my car keys, does that mean my car doesn't exist anymore?",
  "If life is a simulation, can I at least get some cheat codes?",
  "Are my dreams just reruns of life or is the universe low on ideas?",
  "What if aliens have already visited but just looked at us and went ‘no thanks’?",
  "Does the universe have a sense of humor, or is it just mocking me?",
  "If I'm alone in the universe, does that mean I don't have to share my pizza?",
  "Is life just a cosmic game of hide and seek and I'm really bad at it?",
  "If I leave a party early, do I still exist for the rest of the guests?",
  "What if I’m just a side quest in someone else’s video game?",
  "If the universe is expanding, why can't I ever find more closet space?",
  "Is the answer to everything just ‘try turning it off and on again’?",
  "If I’m mostly empty space, why do I need a bigger chair?",
  "What if gravity is just Earth’s way of hugging me too tight?",
  "Do my pets think I’m weird for talking to them or do they talk about me behind my back?",
  "Is déjà vu just the universe replaying my life in slow motion?",
  "What if my phone autocorrect knows more about me than I do?",
  "If life is a highway, why is there so much construction?",
  "Can I ever be truly free if I’m always losing my phone charger?",
  "Is the ‘light at the end of the tunnel’ just my WiFi reconnecting?",
  "If I change my mind about something, was I wrong, or am I just evolving?",
  "If I spend too much time questioning my existence, will my laundry ever get done?",
  "Is the universe infinite, or just my list of unanswered emails?",
  "If I could time travel, would I just use it to fix my typos?",
  "Do I control my thoughts, or do they control me while I’m trying to sleep?",
  "Why do I only get life-changing insights at 3 AM?",
  "What if my purpose is to distract other people from finding their purpose?",
  "If the world is my oyster, where’s my pearl?",
  "Why is the road to self-discovery always under construction?",
  "If I learn from my mistakes, why am I such a genius at making them?",
  "Is life just one big buffering symbol, and I'm the one that forgot to hit ‘play’?",
  "If I forget why I walked into a room, does that mean I cease to exist there?",
  "What if the Hokey Pokey really *is* what it's all about?",
  "Is my life one big blooper reel or just a bad first draft?",
  "Is my shadow just trying to catch up with me, or does it know something I don’t?",
  "If the universe has no center, does that mean I still get to be special?",
  "If I am what I eat, does that make me a walking burrito?",
  "If I speak in my sleep, am I giving away all my existential secrets?",
  "Is happiness just the absence of responsibility… or WiFi?",
  "Why do I remember every embarrassing moment but forget where I put my keys?",
  "If I hit 'undo' on my choices, would I ever stop clicking?",
  "Is life really about the journey, or did someone just forget to install a map?",
  "Do I need a purpose, or can I just vibe through the universe?",
  "If I’m late to my own thoughts, do they still count?",
  "If I’m the center of my universe, why does my coffee keep going cold?",
  "What if life is just one long tutorial and I’ve skipped all the instructions?",
  "If I’m lost in thought, does that mean I need GPS for my brain?",
  "If I stare into the void, does the void eventually get bored and wander off?",
  "If I’m just stardust, why don’t I feel more sparkly?",
  "What if I’m just the NPC in someone else’s simulation?",
  "Is the glass half full, or just in need of a refill?",
  "If life gives me lemons, can I exchange them for pizza?",
  "Why do I always find meaning in fortune cookies and nowhere else?",
  "If I exist in someone else's memory, do I need to pay rent there?",
  "Why is my brain so good at creating problems, but so bad at solving them?",
  "What if my biggest life decision is what to order for dinner?",
  "If I shout into the void, will it eventually answer with sarcasm?",
  "Is the 'meaning of life' just a WiFi password I haven’t found yet?",
  "Why do I only question reality after I've lost the TV remote?",
  "Is it possible I was born just to procrastinate the big questions?",
  "If the world is a stage, when’s intermission?",
  "Am I just waiting for someone to tell me to 'insert coin to continue'?",
  "If I blinked and missed my destiny, can I get a rewind?",
  "If I overthink everything, do I eventually create my own multiverse?",
  "Why is the grass always greener where the WiFi is stronger?",
  "If I’m the protagonist, why is my life filled with plot holes?",
  "Is the final boss of life just a super long password reset?",
  "If I am the sum of my choices, why do I keep forgetting to carry the 1?",
  "If life’s a box of chocolates, am I stuck with the weird coconut one?",
  "What if the universe’s ultimate question is just ‘did you try turning it off and on?’",
  "If I could time travel, would I use it just to avoid awkward conversations?",
  "What if reality is just an elaborate meme and I’m not in on the joke?",
  "If I get lost in thought, does anyone send out a search party?",
  "Why do I always think of the perfect comeback hours after the conversation?",
  "If I hit 'refresh' on my life, will the bugs finally go away?",
  "Have my cumulative life choices led me to click this button?",
];

function setScreenToBlackWithQuestion() {
  const cryButton = document.getElementById("button");
  const question = document.getElementById("question");
  const dot = document.querySelector(".dot");
  dot.classList.add("animate");
  const randomIndex = Math.floor(
    Math.random() * humorousExistentialQuestions.length
  );
  cryButton.style.display = "none";
  //   document.body.style.backgroundColor = "black";
  question.innerHTML = humorousExistentialQuestions[randomIndex];
  question.style.color = "white";
  setTimeout(() => {
    window.close();
  }, 4000);
}
